#! /usr/bin/env php

<?php

use Symfony\Component\Console\Application ;
use Symfony\Component\Console\Input\InputInterface ;
use Symfony\Component\Console\Output\OutputInterface ;
use Symfony\Component\Console\Input\InputArgument ;


if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application( "Wordpress Installer" , "1.0" ) ;

$app->add( new \WP\Installer( new \GuzzleHttp\Client() ));

$app->run();